"""Merged: existing + extracted from 5维整理版 PDFs"""

MARKETING_KNOWLEDGE = [
    {"id": "HW-MKG-001", "title": "SHEIN斋月营销", "content": "SHEIN在斋月推出Modest Fashion专题，传统Abaya与现代色彩结合；中东面孔模特；TikTok #sheinhaul挑战；AR试穿提升转化率25%。", "source": "5维/营销表达维/营销案例.docx", "dimension": "marketing", "tags": ["SHEIN", "斋月"]},
    {"id": "HW-MKG-002", "title": "SHEIN情感连接营销", "content": "SHEIN在利雅得发放开斋水和椰枣做公益营销，与本土7awi Media Group合作内容叙事，建立品牌情感连接。", "source": "5维/营销表达维/营销案例.docx", "dimension": "marketing", "tags": ["SHEIN", "公益"]},
    {"id": "HW-MKG-003", "title": "Namshi Snapchat营销", "content": "Namshi在Snapchat使用Sponsored Snaps，素材像朋友发的短视频；集成AR试穿滤镜。", "source": "5维/营销表达维/营销案例.docx", "dimension": "marketing", "tags": ["Snapchat"]},
    {"id": "HW-MKG-004", "title": "Styli WhatsApp营销", "content": "Styli用WhatsApp代替Email营销，沙特WhatsApp读取率远高于其他渠道；不同城市推送不同优惠。", "source": "5维/营销表达维/营销案例.docx", "dimension": "marketing", "tags": ["WhatsApp"]},
    {"id": "HW-MKG-005", "title": "Modanisa微影响力者矩阵", "content": "Modanisa大量布局微影响力者，沙特消费者对熟人推荐和社区口碑信任度极高。", "source": "5维/营销表达维/营销案例.docx", "dimension": "marketing", "tags": ["KOL"]},
    {"id": "V3-MKG-001", "title": "迎接吉庆斋月。✨ 穿上我们的真丝改良阿巴雅，去赴最华丽的开斋宴吧。", "content": "迎接吉庆斋月。✨ 穿上我们的真丝改良阿巴雅，去赴最华丽的开斋宴吧。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月开斋宴穿搭", "节日营销"]},
    {"id": "V3-MKG-002", "title": "苏赫尔（封斋饭）时分的松弛美学。亚麻面料，透气干爽，在利雅得的夏夜享受宁静。", "content": "苏赫尔（封斋饭）时分的松弛美学。亚麻面料，透气干爽，在利雅得的夏夜享受宁静。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月封斋饭穿搭", "节日营销"]},
    {"id": "V3-MKG-003", "title": "由于斋月期间沙特物流工作时间调整，建议您提前加购，确保开斋节前完美上身。", "content": "由于斋月期间沙特物流工作时间调整，建议您提前加购，确保开斋节前完美上身。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月物流调整提示", "节日营销"]},
    {"id": "V3-MKG-004", "title": "斋月吉庆！全场满 300 SAR 立享免邮，点击链接查看专属优惠。", "content": "斋月吉庆！全场满 300 SAR 立享免邮，点击链接查看专属优惠。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月免邮福利", "节日营销"]},
    {"id": "V3-MKG-005", "title": "展现内敛之美，专为中东女性定制的斋月系列现货发售。", "content": "展现内敛之美，专为中东女性定制的斋月系列现货发售。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月保守时尚定位", "节日营销"]},
    {"id": "V3-MKG-006", "title": "穿上新品长裙，成为斋月晚宴中最闪耀的女神。", "content": "穿上新品长裙，成为斋月晚宴中最闪耀的女神。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月晚宴社交", "节日营销"]},
    {"id": "V3-MKG-007", "title": "输入专属折扣码【RAMADAN15】，立刻享受 85 折优惠。", "content": "输入专属折扣码【RAMADAN15】，立刻享受 85 折优惠。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月折扣催单", "节日营销"]},
    {"id": "V3-MKG-009", "title": "沙特本地仓发货，支持 Mada 卡和 Apple Pay 极速结算。", "content": "沙特本地仓发货，支持 Mada 卡和 Apple Pay 极速结算。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月时效保障", "节日营销"]},
    {"id": "V3-MKG-010", "title": "专为沙特 Z 世代定制的现代改良保守时尚。", "content": "专为沙特 Z 世代定制的现代改良保守时尚。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["斋月年轻消费群体", "节日营销"]},
    {"id": "V3-MKG-011", "title": "开斋节快乐！全家人的节日新衣都在这里，满 500 SAR 还能用 Tabby 免息分期。", "content": "开斋节快乐！全家人的节日新衣都在这里，满 500 SAR 还能用 Tabby 免息分期。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["开斋节全家大促", "节日营销"]},
    {"id": "V3-MKG-012", "title": "逃离城市，奔向吉达海滩！宰牲节度假休闲服饰系列全新上线，防晒又清凉。", "content": "逃离城市，奔向吉达海滩！宰牲节度假休闲服饰系列全新上线，防晒又清凉。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["宰牲节度假服饰", "节日营销"]},
    {"id": "V3-MKG-013", "title": "快点！抢购最后一波开斋节现货服饰，尺码有限！", "content": "快点！抢购最后一波开斋节现货服饰，尺码有限！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["开斋节尾盘抢购", "节日营销"]},
    {"id": "V3-MKG-014", "title": "用一件奢华钉珠 Abaya，开启你的节日穿搭。", "content": "用一件奢华钉珠 Abaya，开启你的节日穿搭。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["节日高客单定制", "节日营销"]},
    {"id": "V3-MKG-015", "title": "愿您岁岁今朝，[品牌名] 祝全体沙特朋友宰牲节快乐。", "content": "愿您岁岁今朝，[品牌名] 祝全体沙特朋友宰牲节快乐。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["宰牲节传统祝愿", "节日营销"]},
    {"id": "V3-MKG-016", "title": "购买节日礼盒，免费赠送绿色烫金精美礼纸包装。", "content": "购买节日礼盒，免费赠送绿色烫金精美礼纸包装。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["节日礼盒增值服务", "节日营销"]},
    {"id": "V3-MKG-017", "title": "穿上新衣服去走亲访友，展现沙特男士的干练与体面。 ", "content": "穿上新衣服去走亲访友，展现沙特男士的干练与体面。 ", "source": "v3/营销表达", "dimension": "marketing", "tags": ["节日男装社交", "节日营销"]},
    {"id": "V3-MKG-018", "title": "假期旅行必备：轻量防皱衬衫，怎么躺都不起皱。", "content": "假期旅行必备：轻量防皱衬衫，怎么躺都不起皱。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["假期差旅出行", "节日营销"]},
    {"id": "V3-MKG-019", "title": "错过了这波大促，就要再等一整年，点击链接查看爆款榜单。", "content": "错过了这波大促，就要再等一整年，点击链接查看爆款榜单。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["大促限时紧迫感", "节日营销"]},
    {"id": "V3-MKG-020", "title": "支持 Tamara 结算，首期仅需 25%，零压力变美。", "content": "支持 Tamara 结算，首期仅需 25%，零压力变美。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["分期付款引导", "节日营销"]},
    {"id": "V3-MKG-021", "title": "绿动沙特，致敬荣耀！🇸🇦 穿上我们的国庆限定潮流绿卫衣，去利雅得大道尽情狂欢。", "content": "绿动沙特，致敬荣耀！🇸🇦 穿上我们的国庆限定潮流绿卫衣，去利雅得大道尽情狂欢。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["沙特国庆节狂欢", "节日营销"]},
    {"id": "V3-MKG-022", "title": "致敬三百年传承。建国日复古传统印花卫衣限量发售。", "content": "致敬三百年传承。建国日复古传统印花卫衣限量发售。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["沙特建国日限定", "节日营销"]},
    {"id": "V3-MKG-023", "title": "展现沙特青年的文化自信。现代高街与传统图腾的完美碰撞。", "content": "展现沙特青年的文化自信。现代高街与传统图腾的完美碰撞。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["国庆文化自信", "节日营销"]},
    {"id": "V3-MKG-024", "title": "庆祝国庆，全场输入优惠码【KSA96】立减 93 SAR！", "content": "庆祝国庆，全场输入优惠码【KSA96】立减 93 SAR！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["国庆数字谐音梗", "节日营销"]},
    {"id": "V3-MKG-025", "title": "用这一抹最正的沙特绿，点亮你的冬日衣橱。", "content": "用这一抹最正的沙特绿，点亮你的冬日衣橱。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["国庆爱国主题色", "节日营销"]},
    {"id": "V3-MKG-026", "title": "祝伟大的沙特人民国庆快乐（愿祖国繁荣昌盛）。", "content": "祝伟大的沙特人民国庆快乐（愿祖国繁荣昌盛）。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["官方标准爱国祝愿", "节日营销"]},
    {"id": "V3-MKG-027", "title": "国庆期间，利雅得、吉达、达曼地区全部免运费配送。", "content": "国庆期间，利雅得、吉达、达曼地区全部免运费配送。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["国庆核心城市免邮", "节日营销"]},
    {"id": "V3-MKG-028", "title": "每一个剪裁都充满敬意，专为现代沙特独立女性打造。", "content": "每一个剪裁都充满敬意，专为现代沙特独立女性打造。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["建国日女性独立主题", "节日营销"]},
    {"id": "V3-MKG-029", "title": "建国日限时买一送一，快来为家人挑选新衣。", "content": "建国日限时买一送一，快来为家人挑选新衣。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["建国日亲情大促", "节日营销"]},
    {"id": "V3-MKG-030", "title": "穿上荣耀，与国家一同迈向 Vision 2030。", "content": "穿上荣耀，与国家一同迈向 Vision 2030。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["2030愿景宏大叙事", "节日营销"]},
    {"id": "V3-MKG-031", "title": "年度最狂欢大促！全场服饰低至 2 折，冬装外套、卫衣现货库存储备完毕。", "content": "年度最狂欢大促！全场服饰低至 2 折，冬装外套、卫衣现货库存储备完毕。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["黄色星期五爆推", "节日营销"]},
    {"id": "V3-MKG-032", "title": "【仅限今晚】White Friday 终极倒计时，购物车宝贝手慢无！", "content": "【仅限今晚】White Friday 终极倒计时，购物车宝贝手慢无！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["白色星期五深夜锁单", "节日营销"]},
    {"id": "V3-MKG-033", "title": "输入终极暗号【FRIDAY50】，全场直接半价，冲！", "content": "输入终极暗号【FRIDAY50】，全场直接半价，冲！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["黑五大促简单粗暴", "节日营销"]},
    {"id": "V3-MKG-034", "title": "别再犹豫了，这是全年最低价，支持 STC Pay 一键支付。", "content": "别再犹豫了，这是全年最低价，支持 STC Pay 一键支付。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["沙特本地老牌网银背书", "节日营销"]},
    {"id": "V3-MKG-035", "title": "欧美高街辣妹风，在沙特也能轻松拥有，白五期间全部包邮。", "content": "欧美高街辣妹风，在沙特也能轻松拥有，白五期间全部包邮。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["高街潮流无门槛免邮", "节日营销"]},
    {"id": "V3-MKG-036", "title": "补货已到！利雅得仓发货，3天必达你的手中。", "content": "补货已到！利雅得仓发货，3天必达你的手中。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["本地海外仓极速送达", "节日营销"]},
    {"id": "V3-MKG-037", "title": "满 200 SAR 立减 50 SAR，点击下方链接领取无门槛券。 ", "content": "满 200 SAR 立减 50 SAR，点击下方链接领取无门槛券。 ", "source": "v3/营销表达", "dimension": "marketing", "tags": ["无门槛阶梯满减", "节日营销"]},
    {"id": "V3-MKG-038", "title": "你的衣橱需要更新了，用最划算的价格承包你一整年的时髦。", "content": "你的衣橱需要更新了，用最划算的价格承包你一整年的时髦。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["高频更新复购引流", "节日营销"]},
    {"id": "V3-MKG-039", "title": "拒绝套路，直降到底！沙特全境支持货到付款（COD）。", "content": "拒绝套路，直降到底！沙特全境支持货到付款（COD）。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["大促结合COD消除疑虑", "节日营销"]},
    {"id": "V3-MKG-040", "title": "伴随冬日初霜，换上 [品牌名] 加绒连帽衫，温暖过冬。", "content": "伴随冬日初霜，换上 [品牌名] 加绒连帽衫，温暖过冬。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["年底换季保暖大衣", "节日营销"]},
    {"id": "V3-MKG-041", "title": "你好亲爱的，我们非常喜欢你在利雅得展现的时尚品味。想送你一套最新的秋季长裙系列。", "content": "你好亲爱的，我们非常喜欢你在利雅得展现的时尚品味。想送你一套最新的秋季长裙系列。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["海外红人主动建联开发", "红人营销"]},
    {"id": "V3-MKG-042", "title": "我们为你生成了专属粉丝折扣码【博主名字10】，享有 15% 销售提成。", "content": "我们为你生成了专属粉丝折扣码【博主名字10】，享有 15% 销售提成。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人分销返佣分润机制", "红人营销"]},
    {"id": "V3-MKG-043", "title": "亲爱的，包裹已经送达利雅得，请注意查收来自 SMSA 快递的短信。", "content": "亲爱的，包裹已经送达利雅得，请注意查收来自 SMSA 快递的短信。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人样品寄送物流追踪", "红人营销"]},
    {"id": "V3-MKG-044", "title": "看到你穿上我们衣服的 Snapchat 视频了，简直太美了！", "content": "看到你穿上我们衣服的 Snapchat 视频了，简直太美了！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人产出素材后赞美黏性", "红人营销"]},
    {"id": "V3-MKG-045", "title": "我们可以为你下一条 TikTok 短视频购买 30 天的广告推流授权。", "content": "我们可以为你下一条 TikTok 短视频购买 30 天的广告推流授权。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["广告素材授权谈判", "红人营销"]},
    {"id": "V3-MKG-046", "title": "专为沙特红人定制：我们提供全线尺码，完美贴合身材曲线。", "content": "专为沙特红人定制：我们提供全线尺码，完美贴合身材曲线。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人尺码包容度卖点", "红人营销"]},
    {"id": "V3-MKG-047", "title": "期待与您长期合作，我们可以为您定制带有您名字的独家联名款。", "content": "期待与您长期合作，我们可以为您定制带有您名字的独家联名款。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["头部红人长期联名合同", "红人营销"]},
    {"id": "V3-MKG-049", "title": "收到包裹后如果有任何不合身，我们立马为您重新安排本地顺丰取件。", "content": "收到包裹后如果有任何不合身，我们立马为您重新安排本地顺丰取件。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["逆向物流逆换货安抚", "红人营销"]},
    {"id": "V3-MKG-051", "title": "姑娘们！看这里！这款高街卫衣版型超赞，完全不挑身材，超级显瘦！", "content": "姑娘们！看这里！这款高街卫衣版型超赞，完全不挑身材，超级显瘦！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["直播/视频带货黄金开头", "红人营销"]},
    {"id": "V3-MKG-052", "title": "不要再买错长裙了！沙特女生买衣服必须注意的3个避坑指南！", "content": "不要再买错长裙了！沙特女生买衣服必须注意的3个避坑指南！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["短视频黄金3秒吸睛避坑", "红人营销"]},
    {"id": "V3-MKG-053", "title": "震惊！这件媲美大牌质感的西装，在我们的直播间居然只要 99 SAR？", "content": "震惊！这件媲美大牌质感的西装，在我们的直播间居然只要 99 SAR？", "source": "v3/营销表达", "dimension": "marketing", "tags": ["大牌平替低价冲击力", "红人营销"]},
    {"id": "V3-MKG-054", "title": "穿着它去和朋友探店喝咖啡，出片率简直 100%！", "content": "穿着它去和朋友探店喝咖啡，出片率简直 100%！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["利雅得流行咖啡探店穿搭", "红人营销"]},
    {"id": "V3-MKG-055", "title": "兄弟们，别再穿千篇一律的纯白袍了，尝试一下这套美式复古工装。", "content": "兄弟们，别再穿千篇一律的纯白袍了，尝试一下这套美式复古工装。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["破除传统单一男袍男装", "红人营销"]},
    {"id": "V3-MKG-056", "title": "面料绝了，抗皱易打理，丢进洗衣机完全不变形，省时省力。", "content": "面料绝了，抗皱易打理，丢进洗衣机完全不变形，省时省力。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["易打理高抗皱痛点", "红人营销"]},
    {"id": "V3-MKG-057", "title": "很多利雅得的大博主都在穿同款，今天在我们这里，直接给到工厂出厂价。", "content": "很多利雅得的大博主都在穿同款，今天在我们这里，直接给到工厂出厂价。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人同款源头工厂背书", "红人营销"]},
    {"id": "V3-MKG-058", "title": "全场包邮！今天下单，最快后天就能送到你家门口。", "content": "全场包邮！今天下单，最快后天就能送到你家门口。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["极速出货时效承诺", "红人营销"]},
    {"id": "V3-MKG-059", "title": "摸摸这个质感，不是地摊货，这是真正的轻奢品质，点击下方小黄车。", "content": "摸摸这个质感，不是地摊货，这是真正的轻奢品质，点击下方小黄车。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["轻奢质感特写引导", "红人营销"]},
    {"id": "V3-MKG-060", "title": "错过了刚才那款的姐妹别哭，下一款更劲爆，手速拉满！", "content": "错过了刚才那款的姐妹别哭，下一款更劲爆，手速拉满！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["漏斗测款快节奏切款", "红人营销"]},
    {"id": "V3-MKG-061", "title": "这面料一点都不透，端庄保守的同时又很有潮流感。", "content": "这面料一点都不透，端庄保守的同时又很有潮流感。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["保守与高街平衡点", "红人营销"]},
    {"id": "V3-MKG-062", "title": "还在为周末聚会穿什么发愁吗？这一套闭眼入，绝对惊艳全场。", "content": "还在为周末聚会穿什么发愁吗？这一套闭眼入，绝对惊艳全场。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["周末家庭/朋友聚会刚需", "红人营销"]},
    {"id": "V3-MKG-063", "title": "输入我的专属代码，直接帮你省下一杯星巴克的钱，冲！", "content": "输入我的专属代码，直接帮你省下一杯星巴克的钱，冲！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["性价比让利引导", "红人营销"]},
    {"id": "V3-MKG-064", "title": "仅限今天！沙特地区首单购买还送定制潮流丝巾一条。", "content": "仅限今天！沙特地区首单购买还送定制潮流丝巾一条。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["首单赠送配饰裂变", "红人营销"]},
    {"id": "V3-MKG-065", "title": "用最少的钱，穿出最有钱的范儿，这就是我们品牌的魔力。", "content": "用最少的钱，穿出最有钱的范儿，这就是我们品牌的魔力。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["中产阶层阶级认同", "红人营销"]},
    {"id": "V3-MKG-066", "title": "你好，可以把您的收货地址和电话发给我们吗？", "content": "你好，可以把您的收货地址和电话发给我们吗？", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人开发极简打招呼", "红人营销"]},
    {"id": "V3-MKG-067", "title": "已经为你备注了利雅得加急，快递小哥会双手奉上。", "content": "已经为你备注了利雅得加急，快递小哥会双手奉上。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人样品加急备注", "红人营销"]},
    {"id": "V3-MKG-068", "title": "您在沙特女孩中非常有影响力，我们非常渴望能与您共创内容。", "content": "您在沙特女孩中非常有影响力，我们非常渴望能与您共创内容。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["夸赞博主本地影响力", "红人营销"]},
    {"id": "V3-MKG-069", "title": "这款衣服的设计灵感来源于吉达的落日，非常衬您的肤色。", "content": "这款衣服的设计灵感来源于吉达的落日，非常衬您的肤色。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["设计概念本地化包装", "红人营销"]},
    {"id": "V3-MKG-070", "title": "我们已经将佣金比例调高到了 20%，每次粉丝下单您都能实时收到通知。", "content": "我们已经将佣金比例调高到了 20%，每次粉丝下单您都能实时收到通知。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["高佣金吸引红人带货", "红人营销"]},
    {"id": "V3-MKG-071", "title": "下周我们将举行独立站沙特闪购夜，欢迎您来做客我们的直播间。", "content": "下周我们将举行独立站沙特闪购夜，欢迎您来做客我们的直播间。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["独立站闪购夜红人引流", "红人营销"]},
    {"id": "V3-MKG-072", "title": "您的穿搭视频在我们中国团队里传阅，大家都觉得您太高级了。", "content": "您的穿搭视频在我们中国团队里传阅，大家都觉得您太高级了。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["团队层面的情绪价值", "红人营销"]},
    {"id": "V3-MKG-073", "title": "没问题亲爱的，我们马上把中码换成大码发给您。", "content": "没问题亲爱的，我们马上把中码换成大码发给您。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["尺码纠错快速响应", "红人营销"]},
    {"id": "V3-MKG-074", "title": "期待您的返图，我们会把它放在独立站的首页面上作为海外买家秀。", "content": "期待您的返图，我们会把它放在独立站的首页面上作为海外买家秀。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["买家秀独立站主页授权", "红人营销"]},
    {"id": "V3-MKG-075", "title": "节日将至，提前祝您和家人长假愉快，阖家幸福。", "content": "节日将至，提前祝您和家人长假愉快，阖家幸福。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["开斋节红人关怀", "红人营销"]},
    {"id": "V3-MKG-076", "title": "专属折扣码已生效：【博主名字EXCLU】。", "content": "专属折扣码已生效：【博主名字EXCLU】。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["独家折扣代码同步", "红人营销"]},
    {"id": "V3-MKG-077", "title": "我们注重每一个细节，从吊牌到面料，绝不让您的粉丝失望。", "content": "我们注重每一个细节，从吊牌到面料，绝不让您的粉丝失望。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["红人带货质量无忧保证", "红人营销"]},
    {"id": "V3-MKG-078", "title": "没关系亲爱的，您可以选择您最喜欢的任意时间段发布。", "content": "没关系亲爱的，您可以选择您最喜欢的任意时间段发布。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["给博主创作自由度松绑", "红人营销"]},
    {"id": "V3-MKG-079", "title": "下一季的国庆节限定，我们将为您保留全球首发评测资格。", "content": "下一季的国庆节限定，我们将为您保留全球首发评测资格。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["下季度爆款优先评测权", "红人营销"]},
    {"id": "V3-MKG-080", "title": "感谢您的建议，我们会针对沙特女性的身高将长裙裙摆缩短2公分。", "content": "感谢您的建议，我们会针对沙特女性的身高将长裙裙摆缩短2公分。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["虚心听取本地版型建议", "红人营销"]},
    {"id": "V3-MKG-081", "title": "您好，您的货到付款包裹已发往利雅得。请提前准备好 150 SAR 现金或银行卡。", "content": "您好，您的货到付款包裹已发往利雅得。请提前准备好 150 SAR 现金或银行卡。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["COD包裹发出硬化锁定", "渠道与老客"]},
    {"id": "V3-MKG-082", "title": "【重要提示】连续两次未能联系到您。包裹将在24小时后退回中国总仓。", "content": "【重要提示】连续两次未能联系到您。包裹将在24小时后退回中国总仓。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["二次拒签边缘强制召回", "渠道与老客"]},
    {"id": "V3-MKG-083", "title": "如果您因为工作忙无法亲自签收，可以回复短信授权放在 RedBox（本地智能快递柜）。", "content": "如果您因为工作忙无法亲自签收，可以回复短信授权放在 RedBox（本地智能快递柜）。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["改寄本地智能快递柜", "渠道与老客"]},
    {"id": "V3-MKG-084", "title": "您的包裹包含您最喜欢的节日礼服，请务必保持手机畅通，避免被快递员退单。", "content": "您的包裹包含您最喜欢的节日礼服，请务必保持手机畅通，避免被快递员退单。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["核心痛点唤醒降低退货", "渠道与老客"]},
    {"id": "V3-MKG-085", "title": "更改配送时间或地址？别着急，点击此链接直接与沙特本地快递小哥对接。", "content": "更改配送时间或地址？别着急，点击此链接直接与沙特本地快递小哥对接。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["给买家下放修改配送自由", "渠道与老客"]},
    {"id": "V3-MKG-086", "title": "货到付款用户请注意：按时签收将提升您的独立站信用额度，解锁下次免预付特权。", "content": "货到付款用户请注意：按时签收将提升您的独立站信用额度，解锁下次免预付特权。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["COD信用评级约束教育", "渠道与老客"]},
    {"id": "V3-MKG-087", "title": "快递员反馈您的电话无法接通，请问您方便提供一个备用联系电话吗？", "content": "快递员反馈您的电话无法接通，请问您方便提供一个备用联系电话吗？", "source": "v3/营销表达", "dimension": "marketing", "tags": ["买家电话不通索要备用号", "渠道与老客"]},
    {"id": "V3-MKG-088", "title": "您的包裹由于利雅得沙尘暴天气稍微延迟，我们已为您奉上 15 SAR 的延误补偿券。", "content": "您的包裹由于利雅得沙尘暴天气稍微延迟，我们已为您奉上 15 SAR 的延误补偿券。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["沙特常发沙尘暴天气延误", "渠道与老客"]},
    {"id": "V3-MKG-089", "title": "确认要取消订单吗？这件衣服库存仅剩1件了，退回就买不到同款尺码了哦。", "content": "确认要取消订单吗？这件衣服库存仅剩1件了，退回就买不到同款尺码了哦。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["最后一件库存心理压迫", "渠道与老客"]},
    {"id": "V3-MKG-090", "title": "别让心爱的衣服在仓库流浪，它正等待着陪伴你共度周末。", "content": "别让心爱的衣服在仓库流浪，它正等待着陪伴你共度周末。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["感性唤醒老客签收", "渠道与老客"]},
    {"id": "V3-MKG-091", "title": "每一笔按时签收的 COD 订单，我们都将抽取 5% 捐赠给本地慈善基金。", "content": "每一笔按时签收的 COD 订单，我们都将抽取 5% 捐赠给本地慈善基金。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["融入本地宗教慈善合规", "渠道与老客"]},
    {"id": "V3-MKG-092", "title": "收到货后如果不喜欢，可以享受 14 天内无理由免费上门取件退货。", "content": "收到货后如果不喜欢，可以享受 14 天内无理由免费上门取件退货。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["14天无忧免费退换条款", "渠道与老客"]},
    {"id": "V3-MKG-093", "title": "快递员会在每天下午 4 点到晚上 10 点（沙特核心活跃时间）之间派送。", "content": "快递员会在每天下午 4 点到晚上 10 点（沙特核心活跃时间）之间派送。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["规避沙特午休配送时间", "渠道与老客"]},
    {"id": "V3-MKG-094", "title": "为确保顺利收到，请在收到验证码短信时，及时回复“1”确认派送。", "content": "为确保顺利收到，请在收到验证码短信时，及时回复“1”确认派送。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["系统指令确认拦截", "渠道与老客"]},
    {"id": "V3-MKG-095", "title": "[品牌名] 承诺：货到付款，安全无忧，不合适当场换，运费我们出！", "content": "[品牌名] 承诺：货到付款，安全无忧，不合适当场换，运费我们出！", "source": "v3/营销表达", "dimension": "marketing", "tags": ["货到付款打消试错顾虑", "渠道与老客"]},
    {"id": "V3-MKG-096", "title": "钱包无压力！选择 Tamara 结账，分四期免息付款，首期今天只需支付 30 SAR。", "content": "钱包无压力！选择 Tamara 结账，分四期免息付款，首期今天只需支付 30 SAR。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["先买后付Tamara渗透", "渠道与老客"]},
    {"id": "V3-MKG-097", "title": "喜欢就全部拿下！用 Tabby 分期，月供居然不到 50 SAR。", "content": "喜欢就全部拿下！用 Tabby 分期，月供居然不到 50 SAR。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["提升客单价低月供锚定", "渠道与老客"]},
    {"id": "V3-MKG-098", "title": "别担心预算！在我们的店铺用分期付款，零手续费、零利息。", "content": "别担心预算！在我们的店铺用分期付款，零手续费、零利息。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["无利息手续费抗拒消除", "渠道与老客"]},
    {"id": "V3-MKG-099", "title": "现代沙特年轻人的精明消费方式：用明天的钱，穿今天最潮流的衣服。", "content": "现代沙特年轻人的精明消费方式：用明天的钱，穿今天最潮流的衣服。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["迎合Z世代精明消费主义", "渠道与老客"]},
    {"id": "V3-MKG-100", "title": "购物车里的奢华阿巴雅超出预算？点击 Tamara 一键轻松结算。", "content": "购物车里的奢华阿巴雅超出预算？点击 Tamara 一键轻松结算。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["重工高端线分期转化", "渠道与老客"]},
    {"id": "V3-MKG-101", "title": "只要通过沙特手机号验证，即可秒速开通 Tabby 额度，即开即用。", "content": "只要通过沙特手机号验证，即可秒速开通 Tabby 额度，即开即用。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["秒级授信丝滑付款体验", "渠道与老客"]},
    {"id": "V3-MKG-102", "title": "分期结账同样享受全场满减大促，折上折更划算。", "content": "分期结账同样享受全场满减大促，折上折更划算。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["分期结合满减折上折", "渠道与老客"]},
    {"id": "V3-MKG-103", "title": "把你和闺蜜的衣服合并下单，用分期付款，每人每月的预算毫无负担。", "content": "把你和闺蜜的衣服合并下单，用分期付款，每人每月的预算毫无负担。", "source": "v3/营销表达", "dimension": "marketing", "tags": ["闺蜜拼单捆绑销售", "渠道与老客"]},
    {"id": "MARKETING-营销案例-001", "title": "背景：SHEIN 在沙特不仅靠快，更靠对宗教节庆的深度拆解。每年斋月期间，SHEIN 会推出“Modest Fashion（穆斯林时尚）”专题，将传统的 Aba", "content": "背景：SHEIN 在沙特不仅靠快，更靠对宗教节庆的深度拆解。每年斋月期间，SHEIN 会推出“Modest Fashion（穆斯林时尚）”专题，将传统的 Abaya（长袍）与现代流行色彩结合。\n\n视觉本地化：广告模特选择中东面孔，妆容符合当地审美（强调眼妆，整体深邃感）。\n\n社媒裂变： 利用 TikTok 发起 #sheinhaul 挑战，并针对沙特年轻一代（50%人口在30岁以下）推广“AR 试穿”功能，2025 年数据显示该功能将转化率提升25%。\n\nSHEIN 在沙特不仅是低价，其“Ramadan in Every Gesture”系列活动是理解沙特市场“情感连接”的极佳模板。\n\n做法：SHEIN 将营销与公益（如在利雅得发放开斋水和椰枣）结合，以及与本土媒体集团（7awi Media Group）合作进行内容叙事。\n\n报告： SHEIN Strengthens Community Engagement Across Saudi Arabia (2026)\n\n相关参考网址：https://www.sohu.com/a/876059647_123843\n\nhttps://www.sohu.com/a/765823090_121810985\n\nhttps://news.qq.com/rain/a/20230308A03ERV00\n\nhttps://baijiahao.baidu.", "source": "marketing/营销案例.docx", "dimension": "marketing", "tags": []},
    {"id": "MARKETING-营销案例-002", "title": "沙特是全球 Snapchat 渗透率最高的国家之一，用户习惯在 Chat 界面与好友交流。", "content": "沙特是全球 Snapchat 渗透率最高的国家之一，用户习惯在 Chat 界面与好友交流。\n\n创意素材： 使用了“Sponsored Snaps”（赞助快照）。不同于硬广，这些素材看起来像朋友发的短视频，展示了沙特年轻时尚达人穿着绿色调（国庆色）服饰的日常生活。\n\n技术应用： 集成 AR 试穿滤镜，让用户在线试戴具有沙特民族特色的配饰或服饰。\n\n网址：https://forbusiness.snapchat.com/success-stories/namshi?lang=fr-FR\n\nStyli（Landmark 集团旗下）是沙特本土成长最快的快时尚电商，其核心竞争力在于极致的自动化运营。\n\n本地化触达：利用 WhatsApp 代替传统的 Email 进行营销。在沙特，WhatsApp 的消息读取率远高于其他渠道。\n\n动态定价：根据用户在利雅得或吉达等不同城市的浏览习惯，实时推送不同的优惠策略。\n\n库存逻辑： 传统零售周转期为 90 天，Styli 缩短至 45 天。这意味着他们能紧跟 TikTok 上的利雅得潮流。\n\n物流协同：利用沙特当地的微型履约中心（Micro-fulfillment centres），实现大城市（如利雅得、达曼）的“次日达”。\n\n选品倾向：重点开发 Modest Fashion（保守时尚） 的现代变体，例如“长裙+西装外套”的职场女性套装。\n\n网址：htt", "source": "marketing/营销案例.docx", "dimension": "marketing", "tags": []},
    {"id": "MARKETING-营销案例-003", "title": "品牌故事：强调“Self-expression through modesty”（通过保守表达自我），将服饰提升到身份认同的高度。", "content": "品牌故事：强调“Self-expression through modesty”（通过保守表达自我），将服饰提升到身份认同的高度。\n\nhttps://www.everflow.io/post/perfectly-tailored-partnerships-how-modanisa-generated-six-figure-sales-in-less-than-six-months-through-better-partner-fit\n\nhttps://salaamgateway.com/story/modest-fashion-giant-modanisa-lays-out-its-global-expansion-and-market-strategy", "source": "marketing/营销案例.docx", "dimension": "marketing", "tags": []},
]

def get_marketing_knowledge():
    return MARKETING_KNOWLEDGE
